filim_pro/urls.py
from django.urls import path
from . import views

app_name='film_pro'
urlpatterns = [
    path('login', views.login, name='login'),
    path('signup', views.signup, name="signup"),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name="dashboard"),
    path('edit-profile', views.edit_profile, name='edit_profile'),
    path('edit-password', views.edit_password, name='edit_password'),
    path('edit-avatar', views.edit_avatar, name='edit_avatar'),
    path('add-people', views.add_people, name='add_people'),
    path('list-people', views.list_people, name='list_people'),
    path('list-people/<str:query>', views.list_people, name='list_people'),
    path('view-people/<int:id>', views.view_people, name='view_people'),
    path('edit-people/<int:id>', views.edit_people, name='edit_people'),
    path('edit-people-avatar/<int:id>', views.edit_people_avatar, name='edit_people_avatar'),
    path('add-people-photo/<int:id>', views.add_people_photo, name='add_people_photo'),
    path('add-movie', views.add_movie, name='add_movie'),
    path('list-movie', views.list_movie, name='list_movie'),
    path('list-movie/<str:query>', views.list_movie, name='list_movie'),    
    path('view-movie/<int:id>', views.view_movie, name='view_movie'),
    path('edit-movie/<int:id>', views.edit_movie, name='edit_movie'),
    path('edit-movie-avatar/<int:id>', views.edit_movie_avatar, name='edit_movie_avatar'),
    path('add-movie-photo/<int:id>', views.add_movie_photo, name='add_movie_photo'),
    path('edit-movie-cast/<int:id>', views.edit_movie_cast, name='edit_movie_cast'),
    path('edit-movie-crew/<int:id>', views.edit_movie_crew, name='edit_movie_crew'),
    path('search-movie', views.search_movie, name='search_movie'),
]

imdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls'),),
    path('pro/',include('filim_pro.urls',namespace='film_pro'),),
    path('user/',include('filim_user.urls',namespace='film_user'),),
    path('site-admin/',include('site_admin.urls',namespace='site_admin'),)
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/film_pro/edit-profile.html
{% extends 'layout.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero user-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>{{ userdata.firstname }} {{ userdata.lastname }} profile</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span>Profile</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width">
			<div class="col-md-3 col-sm-12 col-xs-12">
					<div class="user-information">
						<div class="user-img" style="margin-bottom: 0px;">
							{% if userdata.profile_photo != '' %}
	 						<a href=""><img src="{{ userdata.profile_photo }}" alt=""><br></a>
	            {% else %}
	 					 <a href=""><img src="{% static 'images/uploads/user-img.png' %}" alt=""><br></a>
	 					 {% endif %}
						  <form action="{% url 'film_pro:edit_avatar' %}" class="user" id="avatar_form" method="post" enctype="multipart/form-data" >
							{% csrf_token %}
							<div class="form-style-1 user-pro" action="#" style="margin-bottom: 0px;">
							<div class="row">
							<div class="col-md-12 form-it">
						  <input type="file" name="change_avatar" value="" style="width: -webkit-fill-available; height: auto; color: red;" />
              </div>
							</div>
						  <div class="row">
							<div class="col-md-12">
							<input class="submit" type="submit" value="save">
							</div>
						  </div>
              </div>
             </form>
						</div>
						<div class="user-fav">
							<p>Account Details</p>
							<ul>
								<li class="active"><a href="javascript:;"><img src="{% static 'icons/accessibility-outline.svg' %}" width="15" />  {{ userdata.firstname }} {{ userdata.lastname }}</a></li>
								<li class="active"><a href="javascript:;"><img src="{% static 'icons/call-outline.svg' %}" width="15" /> {{ userdata.phone }}</a></li>
								<li class="active"><a href="javascript:;"><img src="{% static 'icons/mail-outline.svg' %}" width="15" /> {{ userdata.email }}</a></li>
							</ul>
						</div>
					</div>
			</div>
			<div class="col-md-9 col-sm-12 col-xs-12">
				<div class="form-style-1 user-pro" action="#">
					<form action="{% url 'film_pro:edit_profile' %}" class="user" id="profile_form" method="post" >
						{% csrf_token %}
						{% if messages %}
						<ul class="messages text-center">
						{% for message in messages %}
						 <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
						 {% endfor %}
						 </ul>
						 {% endif %}
						<h4>01. Profile details</h4>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>Mobile number</label>
								<input type="text" placeholder="" value="{{ userdata.phone }}" name="mobile_number">
							</div>
							<div class="col-md-6 form-it">
								<label>Email Address</label>
								<input type="text" placeholder="edward@kennedy.com" value="{{ userdata.email }}" name="email_address" >
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>First Name</label>
								<input type="text" placeholder="Edward" value="{{ userdata.firstname }}" name="firstname" >
							</div>
							<div class="col-md-6 form-it">
								<label>Last Name</label>
								<input type="text" placeholder="Kennedy" value="{{ userdata.lastname }}" name="lastname" >
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>State</label>
								<select name="state">
									<option value="KL" {% if userdata.state == 'KL' %} selected {% endif %} >Kerala</option>
									<option value="KA" {% if userdata.state == 'KA' %} selected {% endif %} >Karnataka</option>
									<option value="TN" {% if userdata.state == 'TN' %} selected {% endif %} >Tamil Nadu</option>
									<option value="AP" {% if userdata.state == 'AP' %} selected {% endif %} >Andhra Pradesh</option>
									<option value="MH" {% if userdata.state == 'MH' %} selected {% endif %} >Maharashtra</option>
									<option value="AN" {% if userdata.state == 'AN' %} selected {% endif %} >Andaman and Nicobar Islands</option>
									<option value="AR" {% if userdata.state == 'AR' %} selected {% endif %} >Arunachal Pradesh</option>
									<option value="AS" {% if userdata.state == 'AS' %} selected {% endif %} >Assam</option>
									<option value="BR" {% if userdata.state == 'BR' %} selected {% endif %} >Bihar</option>
									<option value="CH" {% if userdata.state == 'CH' %} selected {% endif %} >Chandigarh</option>
									<option value="CT" {% if userdata.state == 'CT' %} selected {% endif %} >Chhattisgarh</option>
									<option value="DN" {% if userdata.state == 'DN' %} selected {% endif %} >Dadra and Nagar Haveli</option>
									<option value="DD" {% if userdata.state == 'DD' %} selected {% endif %} >Daman and Diu</option>
									<option value="DL" {% if userdata.state == 'DL' %} selected {% endif %} >Delhi</option>
									<option value="GA" {% if userdata.state == 'GA' %} selected {% endif %} >Goa</option>
									<option value="GJ" {% if userdata.state == 'GJ' %} selected {% endif %} >Gujarat</option>
									<option value="HR" {% if userdata.state == 'HR' %} selected {% endif %} >Haryana</option>
									<option value="HP" {% if userdata.state == 'HP' %} selected {% endif %} >Himachal Pradesh</option>
									<option value="JK" {% if userdata.state == 'JK' %} selected {% endif %} >Jammu and Kashmir</option>
									<option value="JH" {% if userdata.state == 'JH' %} selected {% endif %} >Jharkhand</option>
									<option value="LA" {% if userdata.state == 'LA' %} selected {% endif %} >Ladakh</option>
									<option value="LD" {% if userdata.state == 'LD' %} selected {% endif %} >Lakshadweep</option>
									<option value="MP" {% if userdata.state == 'MP' %} selected {% endif %} >Madhya Pradesh</option>
									<option value="MN" {% if userdata.state == 'MN' %} selected {% endif %} >Manipur</option>
									<option value="ML" {% if userdata.state == 'ML' %} selected {% endif %} >Meghalaya</option>
									<option value="MZ" {% if userdata.state == 'MZ' %} selected {% endif %} >Mizoram</option>
									<option value="NL" {% if userdata.state == 'NL' %} selected {% endif %} >Nagaland</option>
									<option value="OR" {% if userdata.state == 'OR' %} selected {% endif %} >Odisha</option>
									<option value="PY" {% if userdata.state == 'PY' %} selected {% endif %} >Puducherry</option>
									<option value="PB" {% if userdata.state == 'PB' %} selected {% endif %} >Punjab</option>
									<option value="RJ" {% if userdata.state == 'RJ' %} selected {% endif %} >Rajasthan</option>
									<option value="SK" {% if userdata.state == 'SK' %} selected {% endif %} >Sikkim</option>
									<option value="TG" {% if userdata.state == 'TG' %} selected {% endif %} >Telangana</option>
									<option value="TR" {% if userdata.state == 'TR' %} selected {% endif %} >Tripura</option>
									<option value="UP" {% if userdata.state == 'UP' %} selected {% endif %} >Uttar Pradesh</option>
									<option value="UT" {% if userdata.state == 'UT' %} selected {% endif %} >Uttarakhand</option>
									<option value="WB" {% if userdata.state == 'WB' %} selected {% endif %} >West Bengal</option>
								</select>
							</div>
						</div>
						<div class="row">
							<div class="col-md-2">
								<input class="submit" type="submit" value="save">
							</div>
						</div>
					</form>
					<form action="{% url 'film_pro:edit_password' %}" class="password" id="password_form" method="post" >
						{% csrf_token %}
						<h4>02. Change password</h4>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>Old Password</label>
								<input type="text" placeholder="**********" name="old_password" >
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>New Password</label>
								<input type="password" placeholder="***************" name="password" id="password" >
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>Confirm New Password</label>
								<input type="password" placeholder="***************" name="confirm_password">
							</div>
						</div>
						<div class="row">
							<div class="col-md-2">
								<input class="submit" type="submit" value="change">
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'validate/additional-methods.min.js' %}"></script>
<script>
$(document).ready(function(){
$( "#profile_form" ).validate({
 ignore: [],
  rules: {
     firstname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    lastname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    mobile_number: {
      required: true,
      digits: true,
      minlength: 9,
      maxlength: 10,
    },
    email_address: {
      required: true,
      email: true,
      minlength: 8,
      maxlength: 255
    },
  }
});
$( "#password_form" ).validate({
 ignore: [],
  rules: {
		old_password: {
			required: true,
      minlength: 5,
      maxlength: 20,
		},
    password: {
      required: true,
      minlength: 5,
      maxlength: 20,
    },
    confirm_password: {
      required: true,
      minlength: 5,
      maxlength: 20,
      equalTo: "#password"
    },
  }
});
$( "#avatar_form" ).validate({
 ignore: [],
  rules: {
    change_avatar: {
      required: true,
			extension:'png,jpg,jpeg',
      filesize: 2097152,
    },
  }
});
});
</script>
{% endblock %}
<!-- custom js end-->

templates/film_pro/list-movie.html
{% extends 'layout.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero common-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1> movie listing - list</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span> movie listing</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single movie_list">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p>Found <span>{{ data_list|length }} movies</span> in total</p>
					<a href="" class="list"><i class="ion-ios-list-outline active"></i></a>
				</div>

				{% for row in data_list %}
				<div class="movie-item-style-2">
					<img src="{{ row.photo }}" alt="" style="width: 170px !important;" >
					<div class="mv-item-infor">
						<h6><a href="{% url 'film_pro:view_movie' id=row.unique_id %}">{{ row.title }} <span>({{ row.release_date|date:'Y' }})</span></a></h6>

            {% for row1 in rating %}
						{% if row1.movie_id == row.unique_id %}
            <p class="rate"><i class="ion-android-star"></i><span>{{ row1.rating_value }}</span> /10</p>
						{% endif %}
            {% empty %}
						<p class="rate"><i class="ion-android-star"></i><span>0</span> /10</p>
            {% endfor %}


						<p class="describe">{{ row.overview|slice:"0:150" }}...</p>
						<p class="run-time"> Run Time: {{ row.running_time }} min    .     <span>{{ row.certificate }} </span>    .     <span>Release: {{ row.release_date|date:"d M Y" }}</span></p>

						<!--
						<p>Director: <a href="#">Joss Whedon</a></p>
						<p>Stars: <a href="#">Robert Downey Jr.,</a> <a href="#">Chris Evans,</a> <a href="#">  Chris Hemsworth</a></p>


						<a href="{% url 'film_pro:view_movie' id=row.unique_id %}" role="button" class="redbtn pull-right" style="padding: 7px 25px;" >view</a>
            -->
					</div>
				</div>
				{% empty %}
          <span class="error">No movies added yet</span>
        {% endfor %}

				<div class="topbar-filter">
					<label>Movies per page:</label>
					<select>
						<option value="range">5 Movies</option>
						<option value="saab">10 Movies</option>
					</select>
					<div class="pagination2">
						<span>Page 1 of 2:</span>
						<a class="active" href="#">1</a>
						<a href="#">2</a>
						<a href="#"><i class="ion-arrow-right-b"></i></a>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="sidebar">
					<div class="searh-form">
						<h4 class="sb-title">Search for movie</h4>
						<form class="form-style-1" action="" method="POST">
								{% csrf_token %}
							<div class="row">
								<div class="col-md-12 form-it">
									<label>Movie name</label>
									<input type="text" placeholder="Enter keywords" name="movie_name">
								</div>
								<div class="col-md-12 form-it">
									<label>Genres</label>
									<div class="group-ip">
										<select name="genre" multiple="" class="ui fluid dropdown">
											  <option value="">Enter to filter genres</option>
											  <option value="Action">Action</option>
												<option value="Animation">Animation</option>
												<option value="Adventure">Adventure</option>
												<option value="Comedy">Comedy</option>
												<option value="Crime">Crime</option>
												<option value="Drama">Drama</option>
												<option value="Fantasy">Fantasy</option>
												<option value="Historical">Historical</option>
												<option value="Horror">Horror</option>
												<option value="Romance">Romance</option>
												<option value="Thriller">Thriller</option>
												<option value="Western">Western</option>
												<option value="Other">Other</option>
										</select>
									</div>

								</div>

								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<div class="ads">
						<img src="images/uploads/ads1.png" alt="">
					</div>

				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
{% endblock %}
<!-- custom js end-->

templates/film_pro/view-people.html
{% extends 'layout.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero hero3">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- <h1> movie listing - list</h1>
				<ul class="breadcumb">
					<li class="active"><a href="#">Home</a></li>
					<li> <span class="ion-ios-arrow-right"></span> movie listing</li>
				</ul> -->
			</div>
		</div>
	</div>
</div>
<div class="page-single movie-single cebleb-single">
	<div class="container">
		<div class="row ipad-width">
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="mv-ceb">
					<img src="{{ userdata.photo }}" alt="">
				</div>
				<form action="{% url 'film_pro:edit_people_avatar' id=userdata.unique_id %}" class="user" id="avatar_form" method="post" enctype="multipart/form-data" >
				{% csrf_token %}
				<div class="form-style-1 user-pro" action="#" style="margin-bottom: 0px; padding: 15px !important;">
				<div class="row">
				<div class="col-md-12 form-it">
				<input type="file" name="change_avatar" value="" style="width: -webkit-fill-available; height: auto; color: red;" />
				</div>
				</div>
				<div class="row">
				<div class="col-md-12">
				<input class="submit" type="submit" value="Change Picture">
				</div>
				</div>
				</div>
			 </form>
			</div>
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="movie-single-ct">
					<h1 class="bd-hd">{{ userdata.firstname }} {{ userdata.lastname }}</h1>
					<p class="ceb-single">{{ userdata.position }}</p>
					<div class="social-link cebsingle-socail">
						<a href="#"><i class="ion-social-facebook"></i></a>
						<a href="#"><i class="ion-social-twitter"></i></a>
						<a href="#"><i class="ion-social-googleplus"></i></a>
						<a href="#"><i class="ion-social-linkedin"></i></a>
					</div>
					<div class="movie-tabs">
						<div class="tabs">
							<ul class="tab-links tabs-mv">
								<li class="active"><a href="#overviewceb">Overview</a></li>
								<li><a href="#biography"> biography</a></li>
								<li><a href="#mediaceb"> Media</a></li>
								<li><a href="#filmography">filmography</a></li>
							</ul>
						    <div class="tab-content">
						        <div id="overviewceb" class="tab active">
						          <div class="row">
						          <div class="col-md-8 col-sm-12 col-xs-12">
						          <p>{{ userdata.biography|slice:"0:200" }}</p>
											<p class="time"><a href="#">See full bio <i class="ion-ios-arrow-right"></i></a></p>
						          <div class="title-hd-sm">
												<h4>Photos</h4>
												<a href="#" class="time"> {{ userdata_photos|length }} Photos <i class="ion-ios-arrow-right"></i></a>
											</div>

											<div class="mvsingle-item ov-item">

                      <div class="row">
                      <div class="col-md-12">
											  {% if userdata_photos|length > 0 %}
												{% for row1 in userdata_photos %}
													<a class="img-lightbox"  data-fancybox-group="gallery" href="{{ row1.photos }}" ><img src="{{ row1.photos }}" alt="" style="height: 100px; width: 100px;" ></a>
	                      {% endfor %}
                        {% else %}
												<span class="error">No photos added yet</span>
												{% endif %}
											</div>
											</div>

											<div class="row">
                      <div class="col-md-12">
												<form action="{% url 'film_pro:add_people_photo' id=userdata.unique_id %}" class="user" id="photos_form" method="post" enctype="multipart/form-data" >
												{% csrf_token %}
												<div class="form-style-1 user-pro" action="#" style="margin-bottom: 0px; padding: 15px !important;">
												<div class="row">
												<div class="col-md-12 form-it">
												<input type="file" name="add_photo" value="" style="width: -webkit-fill-available; height: auto; color: red;" />
												</div>
												</div>
												<div class="row">
												<div class="col-md-12">
												<input class="submit" type="submit" value="Add Photos">
												</div>
												</div>
												</div>
											 </form>
										 </div>
										 </div>

											</div>

											<div class="title-hd-sm">
												<h4>filmography</h4>
												<a href="#" class="time">Full Filmography<i class="ion-ios-arrow-right"></i></a>
											</div>
											<!-- movie cast -->
											<div class="mvcast-item">
                        {% if userdata_filmography|length > 0 %}
												{% for row_cast in userdata_filmography %}
												<div class="cast-it">
													<div class="cast-left cebleb-film">
														<img src="{{ row_cast.movie.photo }}" alt="" style="height: 50px; width: 50px;" >
														<div>
															<a href="#">{{ row_cast.movie.title }}</a>
															<p class="time"></p>
														</div>

													</div>
													<p>...  {{ row_cast.movie.release_date }}</p>
												</div>
												{% endfor %}
											  {% else %}
                        <span class="error">No filmography added yet</span>
												{% endif %}
											</div>
						            	</div>
						            	<div class="col-md-4 col-xs-12 col-sm-12">
						            		<div class="sb-it">
						            			<h6>Fullname:  </h6>
						            			<p><a href="#">{{ userdata.firstname }} {{ userdata.lastname }}</a></p>
						            		</div>
						            		<div class="sb-it">
						            			<h6>Date of Birth: </h6>
						            			<p>{{ userdata.date_of_birth }}</p>
						            		</div>
						            		<div class="sb-it">
						            			<h6>Country:  </h6>
						            			<p>{{ userdata.country|title }}</p>
						            		</div>
														<div class="sb-it">
														<a href="{% url 'film_pro:edit_people' id=userdata.unique_id %}" role="button" class="redbtn" style="padding: 7px 25px" >Edit</a>
														</div>
														<!--
						            		<div class="sb-it">
						            			<h6>Keywords:</h6>
						            			<p class="tags">
						            				<span class="time"><a href="#">jackman</a></span>
													<span class="time"><a href="#">wolverine</a></span>
													<span class="time"><a href="#">logan</a></span>
													<span class="time"><a href="#">blockbuster</a></span>
													<span class="time"><a href="#">final battle</a></span>
						            			</p>
						            		</div>
                            -->
						            		<div class="ads">
												<img src="images/uploads/ads1.png" alt="">
											</div>
						            	</div>
						            </div>
						        </div>
						        <div id="biography" class="tab">
						           <div class="row">
						            	<div class="rv-hd">
											<div>
												<h3>Biography of</h3>
						       	 				<h2>{{ userdata.firstname }} {{ userdata.lastname }}</h2>
											</div>
						            	</div>
						            	<p>{{ userdata.biography }}</p>
						            </div>
						        </div>
						        <div id="mediaceb" class="tab">
						        	<div class="row">
						        		<div class="rv-hd">
						            		<div>
						            			<h3>Biography of</h3>
					       	 					<h2>{{ userdata.firstname }} {{ userdata.lastname }}</h2>
						            		</div>
						            	</div>

										<div class="title-hd-sm">
											<h4>Photos <span> ({{ userdata_photos|length }})</span></h4>
										</div>

										<div class="mvsingle-item">
											<div class="row">
											<div class="col-md-12">
												{% if userdata_photos|length > 0 %}
												{% for row1 in userdata_photos %}
													<a class="img-lightbox"  data-fancybox-group="gallery" href="{{ row1.photos }}" ><img src="{{ row1.photos }}" alt="" style="height: 100px; width: 100px;" ></a>
												{% endfor %}
                        {% else %}
												<span class="error">No photos added yet</span>
												{% endif %}
											</div>
											</div>
										</div>

						        	</div>
					       	 	</div>
					       	 	<div id="filmography" class="tab">
						        	<div class="row">
						            	<div class="rv-hd">
						            		<div>
						            			<h3>Biography of</h3>
					       	 					<h2>{{ userdata.firstname }} {{ userdata.lastname }}</h2>
						            		</div>

						            	</div>
						            	<div class="topbar-filter">
											<p>Found <span>14 movies</span> in total</p>
											<label>Filter by:</label>
											<select>
												<option value="popularity">Popularity Descending</option>
												<option value="popularity">Popularity Ascending</option>
												<option value="rating">Rating Descending</option>
												<option value="rating">Rating Ascending</option>
												<option value="date">Release date Descending</option>
												<option value="date">Release date Ascending</option>
											</select>
										</div>
										<!-- movie cast -->

										<div class="mvcast-item">
										 {% if userdata_filmography|length > 0 %}
										{% for row_cast in userdata_filmography %}
										<div class="cast-it">
											<div class="cast-left cebleb-film">
												<img src="{{ row_cast.movie.photo }}" alt="" style="height: 50px; width: 50px;" >
												<div>
													<a href="#">{{ row_cast.movie.title }}</a>
													<p class="time"></p>
												</div>

											</div>
											<p>...  {{ row_cast.movie.release_date }}</p>
										</div>
	                  {% endfor %}
										{% else %}
										<span class="error">No filmography added yet</span>
										{% endif %}
										</div>

						            </div>
					       	 	</div>
						    </div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'validate/additional-methods.min.js' %}"></script>
<script>
$(document).ready(function(){
	$( "#avatar_form" ).validate({
	 ignore: [],
	  rules: {
	    change_avatar: {
	      required: true,
				extension:'png,jpg,jpeg',
	      filesize: 2097152,
	    },
	  }
	});
	$( "#photos_form" ).validate({
	 ignore: [],
	  rules: {
	    add_photo: {
	      required: true,
				extension:'png,jpg,jpeg',
	      filesize: 2097152,
	    },
	  }
	});
});
</script>
{% endblock %}
<!-- custom js end-->