filim_pro/urls.py
from django.urls import path
from . import views

app_name='film_pro'
urlpatterns = [
    path('login', views.login, name='login'),
    path('signup', views.signup, name="signup"),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name="dashboard"),
    path('edit-profile', views.edit_profile, name='edit_profile'),
    path('edit-password', views.edit_password, name='edit_password'),
    path('edit-avatar', views.edit_avatar, name='edit_avatar'),
    path('add-people', views.add_people, name='add_people'),
    path('list-people', views.list_people, name='list_people'),
    path('list-people/<str:query>', views.list_people, name='list_people'),
    path('view-people/<int:id>', views.view_people, name='view_people'),
    path('edit-people/<int:id>', views.edit_people, name='edit_people'),
    path('edit-people-avatar/<int:id>', views.edit_people_avatar, name='edit_people_avatar'),
    path('add-people-photo/<int:id>', views.add_people_photo, name='add_people_photo'),
    path('add-movie', views.add_movie, name='add_movie'),
    path('list-movie', views.list_movie, name='list_movie'),
    path('list-movie/<str:query>', views.list_movie, name='list_movie'),    
    path('view-movie/<int:id>', views.view_movie, name='view_movie'),
    path('edit-movie/<int:id>', views.edit_movie, name='edit_movie'),
    path('edit-movie-avatar/<int:id>', views.edit_movie_avatar, name='edit_movie_avatar'),
    path('add-movie-photo/<int:id>', views.add_movie_photo, name='add_movie_photo'),
    path('edit-movie-cast/<int:id>', views.edit_movie_cast, name='edit_movie_cast'),
    path('edit-movie-crew/<int:id>', views.edit_movie_crew, name='edit_movie_crew'),
    path('search-movie', views.search_movie, name='search_movie'),
]

imdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls'),),
    path('pro/',include('filim_pro.urls',namespace='film_pro'),),
    path('user/',include('filim_user.urls',namespace='film_user'),),
    path('site-admin/',include('site_admin.urls',namespace='site_admin'),)
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

site_admin/urls.py
from django.urls import path
from . import views

app_name='site_admin'
urlpatterns = [
        path('', views.login, name="login"),
        path('login', views.login, name="login"),
        path('dashboard', views.dashboard, name="dashboard"),
        path('list-screens', views.list_screens, name="list_screens"),
        path('add-screens', views.add_screens, name="add_screens"),
        path('view-screens', views.view_screens, name="view_screens"),
        path('list-movie', views.list_movie, name='list_movie'),
        path('view-movie/<int:id>', views.view_movie, name='view_movie'),
        path('list-people', views.list_people, name='list_people'),
        path('view-people/<int:id>', views.view_people, name='view_people'),
        path('list-user', views.list_user, name='list_user'),
        path('list-pro', views.list_pro, name='list_pro'),
        path('change-pro-status/<int:id>/<str:status>', views.change_pro_status, name='change_pro_status'),
        path('logout', views.logout, name='logout'),
]

templates/includes/footer.html
{% load static %}
<footer class="ht-footer">
	<div class="container">
		<div class="flex-parent-ft">
			<div class="flex-child-ft item1">
				 <a href="index-2.html"><img class="logo" src="{% static 'images/logo1.png' %}" alt=""></a>
				 <p>5th Avenue st, manhattan<br>
				New York, NY 10001</p>
				<p>Call us: <a href="#">(+01) 202 342 6789</a></p>
			</div>
			<div class="flex-child-ft item2">
				<h4>Resources</h4>
				<ul>
					<li><a href="#">About</a></li>
					<li><a href="#">Blockbuster</a></li>
					<li><a href="#">Contact Us</a></li>
					<li><a href="#">Forums</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Help Center</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item3">
				<h4>Legal</h4>
				<ul>
					<li><a href="#">Terms of Use</a></li>
					<li><a href="#">Privacy Policy</a></li>
					<li><a href="#">Security</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item4">
				<h4>Account</h4>
				<ul>
					<li><a href="#">My Account</a></li>
					<li><a href="#">Watchlist</a></li>
					<li><a href="#">Collections</a></li>
					<li><a href="#">User Guide</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item5">
				<h4>Newsletter</h4>
				<p>Subscribe to our newsletter system now <br> to get latest news from us.</p>
				<form action="#">
					<input type="text" placeholder="Enter your email...">
				</form>
				<a href="#" class="btn">Subscribe now <i class="ion-ios-arrow-forward"></i></a>
			</div>
		</div>
	</div>
	<div class="ft-copyright">
		<div class="ft-left">
			<p><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></p>
		</div>
		<div class="backtotop">
			<p><a href="#" id="back-to-top">Back to top  <i class="ion-ios-arrow-thin-up"></i></a></p>
		</div>
	</div>
</footer>

templates/includes/header.html
<header class="ht-header">
	<div class="container">
    {% include "includes/menu.html" %}
	    <!-- top search form -->
			<form action="{% if request.session.usertype == 'pro' %}{% url 'film_pro:search_movie' %}{% else %}{% url 'film_user:search_movie' %}{% endif %}" method="post" >
				{% csrf_token %}
	    <div class="top-search">
	    	<select name="search_item">
				<option value="movie">Movie</option>
				<option value="people">Celebrity</option>
			</select>
			<input type="text" name="search_value" required placeholder="Search for a movie, celebrity that you are looking for" style="background: none !important;" >
			<input type="submit" value="Search" style="background: none !important; color: #dd003f; font-weight: bold; border: #dd003f thin solid;" />
	    </div>
      </form>

	</div>
</header>

templates/includes/menu.html
{% load static %}
<nav class="navbar navbar-default navbar-custom">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header logo">
        <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <div id="nav-icon1">
          <span></span>
          <span></span>
          <span></span>
        </div>
        </div>
        <a href="index-2.html"><img class="logo" src="{% static 'images/logo1.png' %}" alt="" width="119" height="58"></a>
      </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">

      {% if 'is_logged_in' not in request.session or request.session.usertype == 'user' %}
      <ul class="nav navbar-nav flex-child-menu menu-left">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'film_user:list_movie' %}">Movies</a></li>
        <li><a href="{% url 'film_user:list_people' %}">Celebrity</a></li>
      </ul>
      {% endif %}

      {% if 'is_logged_in' in request.session %}
      <ul class="nav navbar-nav flex-child-menu menu-left">
        <li class="hidden">
        <a href="#page-top"></a>
        </li>
        {% if request.session.usertype == 'user' %}
        <li><a href="{% url 'film_user:dashboard' %}">Dashboard</a></li>
        <li><a href="{% url 'film_user:edit_profile' %}">Edit Profile</a></li>
        {% endif %}
        {% if request.session.usertype == 'pro' %}
        <li><a href="{% url 'film_pro:dashboard' %}">Dashboard</a></li>
        <li><a href="{% url 'film_pro:edit_profile' %}">Edit Profile</a></li>
        <li class="dropdown first">
          <a class="btn btn-default dropdown-toggle lv1" data-toggle="dropdown" data-hover="dropdown">
          People <i class="fa fa-angle-down" aria-hidden="true"></i>
          </a>
          <ul class="dropdown-menu level1">
            <li><a href="{% url 'film_pro:list_people' %}">List People</a></li>
            <li class="it-last"><a href="{% url 'film_pro:add_people' %}">Add People</a></li>
          </ul>
        </li>
        <li class="dropdown first">
          <a class="btn btn-default dropdown-toggle lv1" data-toggle="dropdown" data-hover="dropdown">
          Movie <i class="fa fa-angle-down" aria-hidden="true"></i>
          </a>
          <ul class="dropdown-menu level1">
            <li class="it-last"><a href="{% url 'film_pro:list_movie' %}">List Movie</a></li>
            <li><a href="{% url 'film_pro:add_movie' %}">Add Movie</a></li>
          </ul>
        </li>
        {% endif %}

        {% if request.session.usertype == 'site_admin' %}
        <li><a href="{% url 'site_admin:dashboard' %}">Dashboard</a></li>
        <li class="dropdown first">
          <a class="btn btn-default dropdown-toggle lv1" data-toggle="dropdown" data-hover="dropdown">
          Celebrity <i class="fa fa-angle-down" aria-hidden="true"></i>
          </a>
          <ul class="dropdown-menu level1">
            <li class="it-last"><a href="{% url 'site_admin:list_people' %}">List Celebrity</a></li>
          </ul>
        </li>
        <li class="dropdown first">
          <a class="btn btn-default dropdown-toggle lv1" data-toggle="dropdown" data-hover="dropdown">
          Movie <i class="fa fa-angle-down" aria-hidden="true"></i>
          </a>
          <ul class="dropdown-menu level1">
            <li class="it-last"><a href="{% url 'site_admin:list_movie' %}">List Movie</a></li>
          </ul>
        </li>
        <li><a href="{% url 'site_admin:list_pro' %}">Pro</a></li>
        <li><a href="{% url 'site_admin:list_user' %}">User</a></li>
        {% endif %}

      </ul>
      {% endif %}
      <ul class="nav navbar-nav flex-child-menu menu-right">
        {% if 'is_logged_in' not in request.session %}
        <li class="dropdown first">
          <a class="btn btn-default dropdown-toggle lv1" data-toggle="dropdown" data-hover="dropdown">
          Public Relations (pro) <i class="fa fa-angle-down" aria-hidden="true"></i>
          </a>
          <ul class="dropdown-menu level1">
            <li><a href="{% url 'film_pro:login' %}">log in</a></li>
            <li class="it-last"><a href="{% url 'film_pro:signup' %}">sign up</a></li>
          </ul>
        </li>
        <li class="loginLink"><a class="link_active" href="{% url 'film_user:login' %}">Log In</a></li>
        <li class="btn signupLink"><a href="{% url 'film_user:signup' %}">sign up</a></li>
        {% endif %}

        {% if 'is_logged_in' in request.session %}
        {% if request.session.usertype == 'user' %}
         <li class="btn signupLink"><a href="{% url 'film_user:logout' %}">Log out</a></li>
        {% endif %}
        {% if request.session.usertype == 'pro' %}
         <li class="btn signupLink"><a href="{% url 'film_pro:logout' %}">Log out</a></li>
        {% endif %}
        {% if request.session.usertype == 'site_admin' %}
         <li class="btn signupLink"><a href="{% url 'site_admin:logout' %}">Log out</a></li>
        {% endif %}
        {% endif %}

      </ul>
    </div>
  <!-- /.navbar-collapse -->
  </nav>