imdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls'),),
    path('pro/',include('filim_pro.urls',namespace='film_pro'),),
    path('user/',include('filim_user.urls',namespace='film_user'),),
    path('site-admin/',include('site_admin.urls',namespace='site_admin'),)
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

site_admin/urls.py
from django.urls import path
from . import views

app_name='site_admin'
urlpatterns = [
        path('', views.login, name="login"),
        path('login', views.login, name="login"),
        path('dashboard', views.dashboard, name="dashboard"),
        path('list-screens', views.list_screens, name="list_screens"),
        path('add-screens', views.add_screens, name="add_screens"),
        path('view-screens', views.view_screens, name="view_screens"),
        path('list-movie', views.list_movie, name='list_movie'),
        path('view-movie/<int:id>', views.view_movie, name='view_movie'),
        path('list-people', views.list_people, name='list_people'),
        path('view-people/<int:id>', views.view_people, name='view_people'),
        path('list-user', views.list_user, name='list_user'),
        path('list-pro', views.list_pro, name='list_pro'),
        path('change-pro-status/<int:id>/<str:status>', views.change_pro_status, name='change_pro_status'),
        path('logout', views.logout, name='logout'),
]

site_admin/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class screens(models.Model):
    unique_id=models.AutoField(primary_key=True, null=False)
    screen_name = models.CharField(max_length=255, default='null', null=False)
    building_name = models.CharField(max_length=255, default='null', null=False)
    location = models.CharField(max_length=100, default='null', null=False)
    address = models.CharField(max_length=500, default='null', null=False)
    city = models.CharField(max_length=100, default='null', null=False)
    state = models.CharField(max_length=20000, default='null', null=False)
    photo = models.ImageField(upload_to='FILM_PEOPLE/', blank=True, null=True)
    date_added = models.DateTimeField(default=now, editable=False)

    def __str__(self):
        return self.screen_name

site_admin/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from .models import *
from filim_user.models import *
from filim_pro.models import *
from filim_user.models import registration as user_registration
from filim_pro.models import registration as pro_registration
from django.db.models import Avg, Count
# Create your views here.
def login(request):
    if request.method == 'POST':
            data_record = request.POST
            if data_record['username']=="admin" and data_record['password']=="admin":
                request.session['is_logged_in'] = True
                request.session['email'] = "admin@admin.com"
                request.session['firstname'] = "admin"
                request.session['lastname'] = "admin"
                request.session['user_id'] = 0
                request.session['mobile_number'] = 9999999999
                request.session['usertype'] = 'site_admin'
                return redirect(reverse('site_admin:dashboard'))
            else:
                messages.error(request, 'Invalid credentials!')
                return redirect(reverse('site_admin:login'))
    return render(request, 'site_admin/login.html')

def logout(request):
    del request.session['is_logged_in']
    del request.session['firstname']
    del request.session['lastname']
    del request.session['email']
    del request.session['user_id']
    del request.session['mobile_number']
    del request.session['usertype']
    return redirect(reverse('site_admin:login'))

def dashboard(request):
    return render(request, 'site_admin/dashboard.html')

def list_screens(request):
    data_record = screens.objects.all()
    context = { 'data_record':data_record }
    return render(request, 'site_admin/list-screens.html', context)

def add_screens(request):
    return render(request, 'site_admin/add-screen.html')

def view_screens(request):
    return render(request, 'site_admin/view-screen.html')

def list_movie(request):
    data_list = movie.objects.all()
    rating = movie_rating.objects.values('movie_id').annotate(rating_value=Avg('rating_scale', distinct=True))
    context = { 'data_list': data_list, 'rating': rating }
    return render(request, 'site_admin/list-movie.html', context)

def view_movie(request, id):
    if request.method == 'POST':
        data_record = request.POST
        record = movie_rating(
            user_id=request.session['user_id'],
            movie_id=id,
            review_title=data_record['title'],
            review=data_record['review'],
            rating_scale=data_record['rating'],
            )
        record.save()
        messages.success(request, 'Review added successfully!')
        return redirect(reverse('site_admin:view_movie', args=[id]))

    userdata = movie.objects.get(unique_id=id)
    userdata_photos = movie_photo.objects.filter(movie_id=id)
    userdata_cast = movie_cast_crew.objects.filter(type="cast",movie_id=id)
    userdata_crew = movie_cast_crew.objects.filter(type="crew",movie_id=id)
    userdata_reviews = movie_rating.objects.filter(movie_id=id)
    rating_val = movie_rating.objects.filter(movie_id=id).values('movie_id').annotate(rating_value=Avg('rating_scale', distinct=True),rating_count=Count('rating_scale'))
    context = { 'userdata': userdata, 'userdata_photos':userdata_photos, 'userdata_cast':userdata_cast,'userdata_crew':userdata_crew, 'userdata_rating':rating_val, 'userdata_reviews':userdata_reviews, 'record_id':id }
    return render(request, 'site_admin/view-movie.html', context)

def list_people(request):
    data_list = people.objects.all()
    context = { 'data_list': data_list }
    return render(request, 'site_admin/list-people.html', context)

def view_people(request, id):
    userdata = people.objects.get(unique_id=id)
    userdata_photos = people_photo.objects.filter(people_id=id)
    userdata_filmography = movie_cast_crew.objects.filter(people_id=id)
    context = { 'userdata': userdata, 'userdata_photos':userdata_photos, 'userdata_filmography':userdata_filmography }
    return render(request, 'site_admin/view-people.html', context)

def list_user(request):
    data_list = user_registration.objects.all()
    context = { 'data_list': data_list }
    return render(request, 'site_admin/list-user.html', context)

def list_pro(request):
    data_list = pro_registration.objects.all()
    context = { 'data_list': data_list }
    return render(request, 'site_admin/list-pro.html', context)

def change_pro_status(request, id, status):
    userdata = pro_registration.objects.get(unique_id=id)
    temp_status = "pending"
    if status == "pending":
        temp_status = "active"
    userdata.status = temp_status
    userdata.save()
    messages.success(request, 'Status changed successfully!')
    return redirect(reverse('site_admin:list_pro'))

templates/site_admin/add-screen.html
{% extends 'layout.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero user-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>Add Screen</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span>Screen</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width">
			<div class="col-md-10 col-sm-12 col-xs-12 col-md-offset-1">
				<div class="form-style-1 user-pro" action="#">
					<form action="" class="user" id="profile_form" method="post" enctype="multipart/form-data" >
						{% csrf_token %}
						{% if messages %}
						<ul class="messages text-center">
						{% for message in messages %}
						 <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
						 {% endfor %}
						 </ul>
						 {% endif %}
						<h4>01. Details</h4>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>First Name</label>
								<input type="text" placeholder="First Name" value="" name="firstname" >
							</div>
							<div class="col-md-6 form-it">
								<label>Last Name</label>
								<input type="text" placeholder="Last Name" value="" name="lastname" >
							</div>
						</div>

						<div class="row">
							<div class="col-md-6 form-it">
								<label>Date of Birth</label>
								<input type="date" placeholder="" value="" name="date_of_birth">
							</div>
							<div class="col-md-6 form-it">
								<label>Country</label>
								<select name="country">
								<option value="">Select</option>
                <option value="India">India</option>
                <option value="United Kingdom">United Kingdom</option>
								<option value="Usa">Usa</option>
                <option value="Australia">Australia</option>
                <option value="Srilanka">Srilanka</option>
								<option value="German">German</option>
             		<option value="France">France</option>
							  <option value="Brazil">Brazil</option>
								<option value="Russia">Russia</option>
								</select>
							</div>
						</div>
						<div class="row">
						<div class="col-md-12 form-it">
						<label>Photo</label>
						<<input type="file" name="celeb_photo" value="" style="width: -webkit-fill-available; height: auto;">
						</div>
						</div>
						<div class="row">
						<div class="col-md-12 form-it">
						<label>Biography</label>
            <textarea name="biography"></textarea>
						</div>
						</div>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>Cast / Crew</label>
								<select name="cast_crew">
								<option value="">Select</option>
								<option value="cast">Cast</option>
								<option value="crew">Crew</option>
								</select>
							</div>
							<div class="col-md-6 form-it">
								<label>Postion</label>
								<select name="position" multiple style="height: 130px">
								<option value="actor">Actor</option>
								<option value="actress">Actress</option>
								<option value="director">Director</option>
								<option value="producer">Producer</option>
								<option value="music">Music</option>
								<option value="editor">Editor</option>
								<option value="art">Art</option>
								<option value="costume">Costume</option>
								<option value="makeup">Makeup</option>
								<option value="special_effects">Special Effects</option>
								<option value="visual_effects">Visual Effects</option>
								<option value="stunt">Stunt</option>
								<option value="location">Location</option>
								<option value="script">Script</option>
								<option value="screen_play">Screen Play</option>
								<option value="story">Story</option>
								<option value="others">Others</option>
								</select>
							</div>
						</div>
						<div class="row">
							<div class="col-md-2">
								<input class="submit" type="submit" value="save">
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'validate/additional-methods.min.js' %}"></script>
<script>
$(document).ready(function(){
$( "#profile_form" ).validate({
 ignore: [],
  rules: {
     firstname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    lastname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    date_of_birth: {
      required: true,
    },
		biography: {
      required: true,
      digits: false,
      minlength: 100,
      maxlength: 20000
    },
		position: {
			required: true,
		},
		cast_crew: {
			required: true,
		},
		country: {
     required: true,
		},
    celeb_photo: {
			extension:'png,jpg,jpeg',
		}
  }
});
});
</script>
{% endblock %}
<!-- custom js end-->

templates/site_admin/dashboard.html
{% extends 'layout.html' %}
{% block title %}
Dashboard
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero user-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>{{ request.session.lastname }} profile</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span>Profile</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width">
			<div class="col-md-3 col-sm-12 col-xs-12">
				<div class="user-information">
					<div class="user-img">
						<ul><li class="active"><a href="javascript:;"> ( ADMIN ) </a></li></ul>
					</div>
					<div class="user-fav">
						<p>Account Details</p>
						<ul>
							<li class="active"><a href="javascript:;"><img src="{% static 'icons/accessibility-outline.svg' %}" width="15" /> Admin </a></li>
							<li class="active"><a href="javascript:;"><img src="{% static 'icons/call-outline.svg' %}" width="15" /> 0000 0000 00 </a></li>
							<li class="active"><a href="javascript:;"><img src="{% static 'icons/mail-outline.svg' %}" width="15" /> admin@admin.com </a></li>
						</ul>
					</div>
				</div>

			</div>
			<div class="col-md-9 col-sm-12 col-xs-12">
				<div class="form-style-1 user-pro" action="#">

				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
{% endblock %}
<!-- custom js end-->

templates/site_admin/list-people.html
{% extends 'layout.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero user-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>celebrity listing - list</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span>Profile</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-9 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p class="pad-change">Found <span>1,608 celebrities</span> in total</p>
					<label>Sort by:</label>
					<select>
						<option value="popularity">Popularity Descending</option>
						<option value="popularity">Popularity Ascending</option>
						<option value="rating">Rating Descending</option>
						<option value="rating">Rating Ascending</option>
						<option value="date">Release date Descending</option>
						<option value="date">Release date Ascending</option>
					</select>
					<a href="" class="list"><i class="ion-ios-list-outline active"></i></a>
					<a  href="" class="grid"><i class="ion-grid "></i></a>
				</div>
				{% for row in data_list %}
				<div class="row">
					<div class="col-md-12">
						<div class="ceb-item-style-2">
							<img src="{{ row.photo }}" alt="" width="150">
							<div class="ceb-infor">
								<h2><a href="{% url 'site_admin:view_people' id=row.unique_id %}">{{ row.firstname }} {{ row.lastname }}</a></h2>
								<span>{{ row.position }}, {{ row.country }}</span>
								<p>{{ row.biography|slice:"0:200" }} ....</p>
							</div>
						</div>
					</div>
				</div>
        {% endfor %}
				<div class="topbar-filter">
					<label>Reviews per page:</label>
					<select>
						<option value="range">36 Reviews</option>
						<option value="saab">18 Reviews</option>
					</select>

					<div class="pagination2">
						<span>Page 1 of 6:</span>
						<a class="active" href="#">1</a>
						<a href="#">2</a>
						<a href="#">3</a>
						<a href="#">4</a>
						<a href="#">5</a>
						<a href="#">6</a>
						<a href="#"><i class="ion-arrow-right-b"></i></a>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-xs-12 col-sm-12">
				<div class="sidebar">
						<div class="searh-form">
						<h4 class="sb-title">Search celebrity</h4>
						<form class="form-style-1 celebrity-form" action="#">
							<div class="row">
								<div class="col-md-12 form-it">
									<label>Celebrity name</label>
									<input type="text" placeholder="Enter keywords">
								</div>
								<div class="col-md-12 form-it">
									<label>Celebrity Letter</label>
									<select>
									  <option value="range">A</option>
									  <option value="saab">B</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Category</label>
									<select>
									  <option value="range">Actress</option>
									  <option value="saab">Others</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Year of birth</label>
									<div class="row">
										<div class="col-md-6">
											<select>
											  <option value="range">1970</option>
											  <option value="number">Other</option>
											</select>
										</div>
										<div class="col-md-6">
											<select>
											  <option value="range">1990</option>
											  <option value="number">others</option>
											</select>
										</div>
									</div>
								</div>
								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<div class="ads">
						<img src="images/uploads/ads1.png" alt="">
					</div>
					<div class="celebrities">
						<h4 class="sb-title">featured celebrity</h4>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava1.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Samuel N. Jack</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava2.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Benjamin Carroll</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava3.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Beverly Griffin</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava4.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Justin Weaver</a></h6>
								<span>Actor</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'validate/additional-methods.min.js' %}"></script>
<script>
$(document).ready(function(){
$( "#profile_form" ).validate({
 ignore: [],
  rules: {
     firstname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    lastname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    date_of_birth: {
      required: true,
    },
		biography: {
      required: true,
      digits: false,
      minlength: 100,
      maxlength: 20000
    },
		position: {
			required: true,
		},
		cast_crew: {
			required: true,
		},
		country: {
     required: true,
		},
    celeb_photo: {
			extension:'png,jpg,jpeg',
		}
  }
});
});
</script>
{% endblock %}
<!-- custom js end-->

templates/site_admin/list-pro.html
{% extends 'layout.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'datatables/datatables.css' %}"/>
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero user-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>pro - list</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span>Pro</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single" style="background-color: white;">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-12 col-sm-12 col-xs-12" >
				{% if messages %}
				<ul class="messages text-center">
				{% for message in messages %}
				 <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
				 {% endfor %}
				 </ul>
				 {% endif %}
{% if data_list|length > 0 %}
<table id="myTable"  style="width:100%">
				<thead>
						<tr>
								<th width="10">#</th>
								<th>Full Name</th>
								<th>Email</th>
								<th>Phone</th>
								<th>State</th>
								<th>Date Added</th>
								<th>Status</th>
						</tr>
				</thead>
				<tbody>
{% for row in data_list %}
						<tr>
								<td> {{ forloop.counter }} </td>
								<td>{{ row.firstname }} {{ row.lastname }}</td>
								<td>{{ row.email }}</td>
								<td>{{ row.phone }}</td>
								<td>{{ row.state }}</td>
								<td>{{ row.date_added }}</td>
								<td>
									{% if row.status == 'active'  %}
							<div class="cate">
	    					<span class="green"><a href="#" tabindex="0">Active</a></span>
	    				</div>
                 <a href="change-pro-status/{{ row.unique_id }}/{{ row.status }}" role="button"  style="background: none !important; color: green; font-weight: bold; border: green thin solid;text-transform: uppercase;">Change Status</a>
                 {% else %}
								 <div class="cate">
								  <span class="orange"><a href="#" tabindex="0">Pending</a></span>
									</div>
								 <a href="change-pro-status/{{ row.unique_id }}/{{ row.status }}" role="button"  style="background: none !important; color: #dd003f; font-weight: bold; border: #dd003f thin solid; text-transform: uppercase;">Change Status</a>
								 {% endif %}
								</td>
						</tr>
{% endfor %}
</tbody>
<tfoot>
	<tr>
		<th width="10">#</th>
		<th>Full Name</th>
		<th>Email</th>
		<th>Phone</th>
		<th>State</th>
		<th>Date Added</th>
		<th>Status</th>
	</tr>
</tfoot>
</table>
{% else %}
<span class="error">No pro added yet.</span>
{% endif %}

			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
<script type="text/javascript" src="{% static 'datatables/datatables.js' %}"></script>
<script>
$(document).ready( function () {
    $('#myTable').DataTable();
} );
</script>
{% endblock %}
<!-- custom js end-->

templates/site_admin/list-screens.html
{% extends 'layout.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero user-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>Screen listing - list</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span>Screen</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-9 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p class="pad-change">Found <span>1,608 celebrities</span> in total</p>
					<label>Sort by:</label>
					<select>
						<option value="popularity">Popularity Descending</option>
						<option value="popularity">Popularity Ascending</option>
						<option value="rating">Rating Descending</option>
						<option value="rating">Rating Ascending</option>
						<option value="date">Release date Descending</option>
						<option value="date">Release date Ascending</option>
					</select>
					<a href="" class="list"><i class="ion-ios-list-outline active"></i></a>
					<a  href="" class="grid"><i class="ion-grid "></i></a>
				</div>
				{% for row in data_list %}
				<div class="row">
					<div class="col-md-12">
						<div class="ceb-item-style-2">
							<img src="{{ row.photo }}" alt="" width="150">
							<div class="ceb-infor">
								<h2><a href="{% url 'film_user:view_people' id=row.unique_id %}">{{ row.firstname }} {{ row.lastname }}</a></h2>
								<span>{{ row.position }}, {{ row.country }}</span>
								<p>{{ row.biography|slice:"0:200" }} ....</p>
							</div>
						</div>
					</div>
				</div>
        {% endfor %}
				<div class="topbar-filter">
					<label>Reviews per page:</label>
					<select>
						<option value="range">36 Reviews</option>
						<option value="saab">18 Reviews</option>
					</select>

					<div class="pagination2">
						<span>Page 1 of 6:</span>
						<a class="active" href="#">1</a>
						<a href="#">2</a>
						<a href="#">3</a>
						<a href="#">4</a>
						<a href="#">5</a>
						<a href="#">6</a>
						<a href="#"><i class="ion-arrow-right-b"></i></a>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-xs-12 col-sm-12">
				<div class="sidebar">
						<div class="searh-form">
						<h4 class="sb-title">Search celebrity</h4>
						<form class="form-style-1 celebrity-form" action="#">
							<div class="row">
								<div class="col-md-12 form-it">
									<label>Celebrity name</label>
									<input type="text" placeholder="Enter keywords">
								</div>
								<div class="col-md-12 form-it">
									<label>Celebrity Letter</label>
									<select>
									  <option value="range">A</option>
									  <option value="saab">B</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Category</label>
									<select>
									  <option value="range">Actress</option>
									  <option value="saab">Others</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Year of birth</label>
									<div class="row">
										<div class="col-md-6">
											<select>
											  <option value="range">1970</option>
											  <option value="number">Other</option>
											</select>
										</div>
										<div class="col-md-6">
											<select>
											  <option value="range">1990</option>
											  <option value="number">others</option>
											</select>
										</div>
									</div>
								</div>
								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<div class="ads">
						<img src="images/uploads/ads1.png" alt="">
					</div>
					<div class="celebrities">
						<h4 class="sb-title">featured celebrity</h4>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava1.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Samuel N. Jack</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava2.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Benjamin Carroll</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava3.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Beverly Griffin</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava4.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Justin Weaver</a></h6>
								<span>Actor</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'validate/additional-methods.min.js' %}"></script>
<script>
$(document).ready(function(){
$( "#profile_form" ).validate({
 ignore: [],
  rules: {
     firstname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    lastname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    date_of_birth: {
      required: true,
    },
		biography: {
      required: true,
      digits: false,
      minlength: 100,
      maxlength: 20000
    },
		position: {
			required: true,
		},
		cast_crew: {
			required: true,
		},
		country: {
     required: true,
		},
    celeb_photo: {
			extension:'png,jpg,jpeg',
		}
  }
});
});
</script>
{% endblock %}
<!-- custom js end-->