filim_pro/urls.py
from django.urls import path
from . import views

app_name='film_pro'
urlpatterns = [
    path('login', views.login, name='login'),
    path('signup', views.signup, name="signup"),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name="dashboard"),
    path('edit-profile', views.edit_profile, name='edit_profile'),
    path('edit-password', views.edit_password, name='edit_password'),
    path('edit-avatar', views.edit_avatar, name='edit_avatar'),
    path('add-people', views.add_people, name='add_people'),
    path('list-people', views.list_people, name='list_people'),
    path('list-people/<str:query>', views.list_people, name='list_people'),
    path('view-people/<int:id>', views.view_people, name='view_people'),
    path('edit-people/<int:id>', views.edit_people, name='edit_people'),
    path('edit-people-avatar/<int:id>', views.edit_people_avatar, name='edit_people_avatar'),
    path('add-people-photo/<int:id>', views.add_people_photo, name='add_people_photo'),
    path('add-movie', views.add_movie, name='add_movie'),
    path('list-movie', views.list_movie, name='list_movie'),
    path('list-movie/<str:query>', views.list_movie, name='list_movie'),    
    path('view-movie/<int:id>', views.view_movie, name='view_movie'),
    path('edit-movie/<int:id>', views.edit_movie, name='edit_movie'),
    path('edit-movie-avatar/<int:id>', views.edit_movie_avatar, name='edit_movie_avatar'),
    path('add-movie-photo/<int:id>', views.add_movie_photo, name='add_movie_photo'),
    path('edit-movie-cast/<int:id>', views.edit_movie_cast, name='edit_movie_cast'),
    path('edit-movie-crew/<int:id>', views.edit_movie_crew, name='edit_movie_crew'),
    path('search-movie', views.search_movie, name='search_movie'),
]

imdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls'),),
    path('pro/',include('filim_pro.urls',namespace='film_pro'),),
    path('user/',include('filim_user.urls',namespace='film_user'),),
    path('site-admin/',include('site_admin.urls',namespace='site_admin'),)
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/film_user/dashboard.html
{% extends 'layout.html' %}
{% block title %}
Dashboard
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero user-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>{{ userdata.firstname }} {{ userdata.lastname }} profile</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span>Profile</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width">
			<div class="col-md-3 col-sm-12 col-xs-12">
				<div class="user-information">
					<div class="user-img" style="margin-bottom: 0px;" >
           {% if userdata.profile_photo != '' %}
						<a href=""><img src="{{ userdata.profile_photo }}" alt=""><br></a>
           {% else %}
					 <a href=""><img src="{% static 'images/uploads/user-img.png' %}" alt=""><br></a>
					 {% endif %}
						<ul><li class="active"><a href="javascript:;"> ( USER ) </a></li></ul>
					</div>
					<div class="user-fav">
						<p>Account Details</p>
						<ul>
							<li class="active"><a href="javascript:;"><img src="{% static 'icons/accessibility-outline.svg' %}" width="15" />  {{ userdata.firstname }} {{ userdata.lastname }}</a></li>
							<li class="active"><a href="javascript:;"><img src="{% static 'icons/call-outline.svg' %}" width="15" /> {{ userdata.phone }}</a></li>
							<li class="active"><a href="javascript:;"><img src="{% static 'icons/mail-outline.svg' %}" width="15" /> {{ userdata.email }}</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-md-9 col-sm-12 col-xs-12">
				<div class="form-style-1 user-pro" action="#">
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
{% endblock %}
<!-- custom js end-->

templates/film_user/edit-profile.html
{% extends 'layout.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero user-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>{{ userdata.firstname }} {{ userdata.lastname }} profile</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span>Profile</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width">
			<div class="col-md-3 col-sm-12 col-xs-12">
					<div class="user-information">
						<div class="user-img" style="margin-bottom: 0px;">
							{% if userdata.profile_photo != '' %}
	 						<a href=""><img src="{{ userdata.profile_photo }}" alt=""><br></a>
	            {% else %}
	 					 <a href=""><img src="{% static 'images/uploads/user-img.png' %}" alt=""><br></a>
	 					 {% endif %}
						  <form action="{% url 'film_user:edit_avatar' %}" class="user" id="avatar_form" method="post" enctype="multipart/form-data" >
							{% csrf_token %}
							<div class="form-style-1 user-pro" action="#" style="margin-bottom: 0px;">
							<div class="row">
							<div class="col-md-12 form-it">
						  <input type="file" name="change_avatar" value="" style="width: -webkit-fill-available; height: auto; color: red;" />
              </div>
							</div>
						  <div class="row">
							<div class="col-md-12">
							<input class="submit" type="submit" value="save">
							</div>
						  </div>
              </div>
             </form>
						</div>
						<div class="user-fav">
							<p>Account Details</p>
							<ul>
								<li class="active"><a href="javascript:;"><img src="{% static 'icons/accessibility-outline.svg' %}" width="15" />  {{ userdata.firstname }} {{ userdata.lastname }}</a></li>
								<li class="active"><a href="javascript:;"><img src="{% static 'icons/call-outline.svg' %}" width="15" /> {{ userdata.phone }}</a></li>
								<li class="active"><a href="javascript:;"><img src="{% static 'icons/mail-outline.svg' %}" width="15" /> {{ userdata.email }}</a></li>
							</ul>
						</div>
					</div>
			</div>
			<div class="col-md-9 col-sm-12 col-xs-12">
				<div class="form-style-1 user-pro" action="#">
					<form action="{% url 'film_user:edit_profile' %}" class="user" id="profile_form" method="post" >
						{% csrf_token %}
						{% if messages %}
						<ul class="messages text-center">
						{% for message in messages %}
						 <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
						 {% endfor %}
						 </ul>
						 {% endif %}
						<h4>01. Profile details</h4>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>Mobile number</label>
								<input type="text" placeholder="" value="{{ userdata.phone }}" name="mobile_number">
							</div>
							<div class="col-md-6 form-it">
								<label>Email Address</label>
								<input type="text" placeholder="edward@kennedy.com" value="{{ userdata.email }}" name="email_address" >
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>First Name</label>
								<input type="text" placeholder="Edward" value="{{ userdata.firstname }}" name="firstname" >
							</div>
							<div class="col-md-6 form-it">
								<label>Last Name</label>
								<input type="text" placeholder="Kennedy" value="{{ userdata.lastname }}" name="lastname" >
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>State</label>
								<select name="state">
									<option value="KL" {% if userdata.state == 'KL' %} selected {% endif %} >Kerala</option>
									<option value="KA" {% if userdata.state == 'KA' %} selected {% endif %} >Karnataka</option>
									<option value="TN" {% if userdata.state == 'TN' %} selected {% endif %} >Tamil Nadu</option>
									<option value="AP" {% if userdata.state == 'AP' %} selected {% endif %} >Andhra Pradesh</option>
									<option value="MH" {% if userdata.state == 'MH' %} selected {% endif %} >Maharashtra</option>
									<option value="AN" {% if userdata.state == 'AN' %} selected {% endif %} >Andaman and Nicobar Islands</option>
									<option value="AR" {% if userdata.state == 'AR' %} selected {% endif %} >Arunachal Pradesh</option>
									<option value="AS" {% if userdata.state == 'AS' %} selected {% endif %} >Assam</option>
									<option value="BR" {% if userdata.state == 'BR' %} selected {% endif %} >Bihar</option>
									<option value="CH" {% if userdata.state == 'CH' %} selected {% endif %} >Chandigarh</option>
									<option value="CT" {% if userdata.state == 'CT' %} selected {% endif %} >Chhattisgarh</option>
									<option value="DN" {% if userdata.state == 'DN' %} selected {% endif %} >Dadra and Nagar Haveli</option>
									<option value="DD" {% if userdata.state == 'DD' %} selected {% endif %} >Daman and Diu</option>
									<option value="DL" {% if userdata.state == 'DL' %} selected {% endif %} >Delhi</option>
									<option value="GA" {% if userdata.state == 'GA' %} selected {% endif %} >Goa</option>
									<option value="GJ" {% if userdata.state == 'GJ' %} selected {% endif %} >Gujarat</option>
									<option value="HR" {% if userdata.state == 'HR' %} selected {% endif %} >Haryana</option>
									<option value="HP" {% if userdata.state == 'HP' %} selected {% endif %} >Himachal Pradesh</option>
									<option value="JK" {% if userdata.state == 'JK' %} selected {% endif %} >Jammu and Kashmir</option>
									<option value="JH" {% if userdata.state == 'JH' %} selected {% endif %} >Jharkhand</option>
									<option value="LA" {% if userdata.state == 'LA' %} selected {% endif %} >Ladakh</option>
									<option value="LD" {% if userdata.state == 'LD' %} selected {% endif %} >Lakshadweep</option>
									<option value="MP" {% if userdata.state == 'MP' %} selected {% endif %} >Madhya Pradesh</option>
									<option value="MN" {% if userdata.state == 'MN' %} selected {% endif %} >Manipur</option>
									<option value="ML" {% if userdata.state == 'ML' %} selected {% endif %} >Meghalaya</option>
									<option value="MZ" {% if userdata.state == 'MZ' %} selected {% endif %} >Mizoram</option>
									<option value="NL" {% if userdata.state == 'NL' %} selected {% endif %} >Nagaland</option>
									<option value="OR" {% if userdata.state == 'OR' %} selected {% endif %} >Odisha</option>
									<option value="PY" {% if userdata.state == 'PY' %} selected {% endif %} >Puducherry</option>
									<option value="PB" {% if userdata.state == 'PB' %} selected {% endif %} >Punjab</option>
									<option value="RJ" {% if userdata.state == 'RJ' %} selected {% endif %} >Rajasthan</option>
									<option value="SK" {% if userdata.state == 'SK' %} selected {% endif %} >Sikkim</option>
									<option value="TG" {% if userdata.state == 'TG' %} selected {% endif %} >Telangana</option>
									<option value="TR" {% if userdata.state == 'TR' %} selected {% endif %} >Tripura</option>
									<option value="UP" {% if userdata.state == 'UP' %} selected {% endif %} >Uttar Pradesh</option>
									<option value="UT" {% if userdata.state == 'UT' %} selected {% endif %} >Uttarakhand</option>
									<option value="WB" {% if userdata.state == 'WB' %} selected {% endif %} >West Bengal</option>
								</select>
							</div>
						</div>
						<div class="row">
							<div class="col-md-2">
								<input class="submit" type="submit" value="save">
							</div>
						</div>
					</form>
					<form action="{% url 'film_user:edit_password' %}" class="password" id="password_form" method="post" >
						{% csrf_token %}
						<h4>02. Change password</h4>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>Old Password</label>
								<input type="text" placeholder="**********" name="old_password" >
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>New Password</label>
								<input type="password" placeholder="***************" name="password" id="password" >
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>Confirm New Password</label>
								<input type="password" placeholder="***************" name="confirm_password">
							</div>
						</div>
						<div class="row">
							<div class="col-md-2">
								<input class="submit" type="submit" value="change">
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'validate/additional-methods.min.js' %}"></script>
<script>
$(document).ready(function(){
$( "#profile_form" ).validate({
 ignore: [],
  rules: {
     firstname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    lastname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    mobile_number: {
      required: true,
      digits: true,
      minlength: 9,
      maxlength: 10,
    },
    email_address: {
      required: true,
      email: true,
      minlength: 8,
      maxlength: 255
    },
  }
});
$( "#password_form" ).validate({
 ignore: [],
  rules: {
		old_password: {
			required: true,
      minlength: 5,
      maxlength: 20,
		},
    password: {
      required: true,
      minlength: 5,
      maxlength: 20,
    },
    confirm_password: {
      required: true,
      minlength: 5,
      maxlength: 20,
      equalTo: "#password"
    },
  }
});
$( "#avatar_form" ).validate({
 ignore: [],
  rules: {
    change_avatar: {
      required: true,
			extension:'png,jpg,jpeg',
      filesize: 2097152,
    },
  }
});
});
</script>
{% endblock %}
<!-- custom js end-->

templates/film_user/list-movie.html
{% extends 'layout.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero common-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1> movie listing - list</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span> movie listing</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single movie_list">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p>Found <span>{{ data_list|length }} movies</span> in total</p>
					<a href="" class="list"><i class="ion-ios-list-outline active"></i></a>
				</div>


				{% for row in data_list %}
				<div class="movie-item-style-2">
					<img src="{{ row.photo }}" alt="" style="width: 170px !important;" >
					<div class="mv-item-infor">
						<h6><a href="{% url 'film_user:view_movie' id=row.unique_id %}">{{ row.title }} <span>({{ row.release_date|date:'Y' }})</span></a></h6>
            {% for row1 in rating %}
						{% if row1.movie_id == row.unique_id %}
            <p class="rate"><i class="ion-android-star"></i><span>{{ row1.rating_value }}</span> /10</p>
						{% endif %}
            {% empty %}
						<p class="rate"><i class="ion-android-star"></i><span>0</span> /10</p>
            {% endfor %}
						<p class="describe">{{ row.overview|slice:"0:150" }}...</p>
						<p class="run-time"> Run Time: {{ row.running_time }} min    .     <span>{{ row.certificate }} </span>    .     <span>Release: {{ row.release_date|date:"d M Y" }}</span></p>
						<!--
						<p>Director: <a href="#">Joss Whedon</a></p>
						<p>Stars: <a href="#">Robert Downey Jr.,</a> <a href="#">Chris Evans,</a> <a href="#">  Chris Hemsworth</a></p>
            -->
					</div>
				</div>
				{% empty %}
          <span class="error">No movies found</span>
        {% endfor %}

				<div class="topbar-filter">

					<div class="pagination2">
						<span>Page 1 of 2:</span>
						<a class="active" href="#">1</a>
						<a href="#">2</a>
						<a href="#"><i class="ion-arrow-right-b"></i></a>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="sidebar">
					<div class="searh-form">
						<h4 class="sb-title">Search for movie</h4>
						<form class="form-style-1" action="{% url 'film_user:list_movie' %}" method="POST">
								{% csrf_token %}
							<div class="row">
								<div class="col-md-12 form-it">
									<label>Movie name</label>
									<input type="text" placeholder="Enter keywords" name="movie_name">
								</div>
								<div class="col-md-12 form-it">
									<label>Genres</label>
									<div class="group-ip">
										<select name="genre" multiple="" class="ui fluid dropdown">
											  <option value="">Enter to filter genres</option>
											  <option value="Action">Action</option>
												<option value="Animation">Animation</option>
												<option value="Adventure">Adventure</option>
												<option value="Comedy">Comedy</option>
												<option value="Crime">Crime</option>
												<option value="Drama">Drama</option>
												<option value="Fantasy">Fantasy</option>
												<option value="Historical">Historical</option>
												<option value="Horror">Horror</option>
												<option value="Romance">Romance</option>
												<option value="Thriller">Thriller</option>
												<option value="Western">Western</option>
												<option value="Other">Other</option>
										</select>
									</div>

								</div>

								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<div class="ads">
						<img src="images/uploads/ads1.png" alt="">
					</div>

				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'validate/additional-methods.min.js' %}"></script>
<script>
$(document).ready(function(){
$( "#profile_form" ).validate({
 ignore: [],
  rules: {
     firstname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    lastname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    date_of_birth: {
      required: true,
    },
		biography: {
      required: true,
      digits: false,
      minlength: 100,
      maxlength: 20000
    },
		position: {
			required: true,
		},
		cast_crew: {
			required: true,
		},
		country: {
     required: true,
		},
    celeb_photo: {
			extension:'png,jpg,jpeg',
		}
  }
});
});
</script>
{% endblock %}
<!-- custom js end-->

templates/film_user/list-people.html
{% extends 'layout.html' %}
{% block title %}
Edit Profile
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero user-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>celebrity listing - list</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span>Profile</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-9 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p class="pad-change">Found <span>{{ data_list|length }} celebrities</span> in total</p>
					<a href="" class="list"><i class="ion-ios-list-outline active"></i></a>
				</div>
				{% for row in data_list %}
				<div class="row">
					<div class="col-md-12">
						<div class="ceb-item-style-2">
							<img src="{{ row.photo }}" alt="" width="150">
							<div class="ceb-infor">
								<h2><a href="{% url 'film_user:view_people' id=row.unique_id %}">{{ row.firstname }} {{ row.lastname }}</a></h2>
								<span>{{ row.position }}, {{ row.country }}</span>
								<p>{{ row.biography|slice:"0:200" }} ....</p>
							</div>
						</div>
					</div>
				</div>
				{% empty %}
					<span class="error">No people found</span>
				{% endfor %}
				<div class="topbar-filter">
					<div class="pagination2">
						<span>Page 1 of 6:</span>
						<a class="active" href="#">1</a>
						<a href="#">2</a>
						<a href="#">3</a>
						<a href="#">4</a>
						<a href="#">5</a>
						<a href="#">6</a>
						<a href="#"><i class="ion-arrow-right-b"></i></a>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-xs-12 col-sm-12">
				<div class="sidebar">
						<div class="searh-form">
						<h4 class="sb-title">Search celebrity</h4>
						<form class="form-style-1 celebrity-form" action="{% url 'film_user:list_people' %}" method="post">
              {% csrf_token %}
							<div class="row">
								<div class="col-md-12 form-it">
									<label>Celebrity name</label>
									<input type="text" placeholder="Enter keywords" name="celebrity_name">
								</div>
								<div class="col-md-12 form-it">
									<label>Celebrity Letter</label>
									<select name="celebrity_letter" >
										<option value="">Select Letter</option>
									  <option value="a">A</option>
									  <option value="b">B</option>
										<option value="c">C</option>
									  <option value="d">D</option>
										<option value="e">E</option>
										<option value="f">F</option>
										<option value="g">G</option>
										<option value="h">H</option>
										<option value="i">I</option>
										<option value="j">J</option>
										<option value="k">K</option>
										<option value="l">L</option>
										<option value="m">M</option>
										<option value="n">N</option>
										<option value="o">O</option>
										<option value="p">P</option>
										<option value="q">Q</option>
										<option value="r">R</option>
										<option value="s">S</option>
										<option value="t">T</option>
										<option value="u">U</option>
										<option value="v">V</option>
										<option value="w">W</option>
										<option value="x">X</option>
										<option value="y">Y</option>
										<option value="z">Z</option>
									</select>
								</div>
								<div class="col-md-12 ">
									<input class="submit" type="submit" value="submit">
								</div>
							</div>
						</form>
					</div>
					<div class="ads">
						<img src="images/uploads/ads1.png" alt="">
					</div>
					<div class="celebrities">
						<h4 class="sb-title">featured celebrity</h4>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava1.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Samuel N. Jack</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava2.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Benjamin Carroll</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava3.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Beverly Griffin</a></h6>
								<span>Actor</span>
							</div>
						</div>
						<div class="celeb-item">
							<a href="#"><img src="images/uploads/ava4.jpg" alt=""></a>
							<div class="celeb-author">
								<h6><a href="#">Justin Weaver</a></h6>
								<span>Actor</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'validate/additional-methods.min.js' %}"></script>
<script>
$(document).ready(function(){
$( "#profile_form" ).validate({
 ignore: [],
  rules: {
     firstname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    lastname: {
      required: true,
      digits: false,
      minlength: 2,
      maxlength: 255
    },
    date_of_birth: {
      required: true,
    },
		biography: {
      required: true,
      digits: false,
      minlength: 100,
      maxlength: 20000
    },
		position: {
			required: true,
		},
		cast_crew: {
			required: true,
		},
		country: {
     required: true,
		},
    celeb_photo: {
			extension:'png,jpg,jpeg',
		}
  }
});
});
</script>
{% endblock %}
<!-- custom js end-->

templates/film_user/login.html
{% extends 'layout.html' %}
{% block title %}
Login
{% endblock %}
{% load static %}
<!-- custom css -->
{% block css %}
{% endblock %}
<!-- custom css end-->
{% block content %}
<div class="hero user-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1>Login</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">Home</a></li>
						<li> <span class="ion-ios-arrow-right"></span>Login</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="page-single">
	<div class="container">
		<div class="row ipad-width">
				<div class="col-md-10 col-sm-12 col-xs-12 col-md-offset-1">
				<div class="form-style-1 user-pro" action="">
					<form action="" class="password"  id="myform" method="post">
						{% csrf_token %}
						{% if messages %}
						<ul class="messages text-center">
						{% for message in messages %}
						 <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
						 {% endfor %}
						 </ul>
						 {% endif %}
						<h4>login here</h4>
						<div class="row">
							<div class="col-md-6 form-it">
								<label>Mobile Number</label>
								<input type="text" placeholder="Mobile Number" name="mobile_number">
							</div>

							<div class="col-md-6 form-it">
								<label>Password</label>
								<input type="password" placeholder="Password" name="password">
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<p><a href="{% url 'film_user:signup' %}" class="custom-link-1 pull-right">Not registered signin here </a></p>
							</div>
						</div>
						<div class="row">
							<div class="col-md-2">
								<input class="submit" type="submit" value="Submit">
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
<!-- custom js -->
{% block js %}
<script src="{% static 'validate/jquery.validate.min.js' %}"></script>
<script src="{% static 'validate/additional-methods.min.js' %}"></script>
<script>
$(document).ready(function(){
$( "#myform" ).validate({
 ignore: [],
  rules: {
    mobile_number: {
      required: true,
      digits: true,
      minlength: 9,
      maxlength: 10,
    },
    password: {
      required: true,
      minlength: 5,
      maxlength: 20,
    },
  }
});
});
</script>
{% endblock %}
<!-- custom js end-->